name: Biome Code Quality

on:
  pull_request:
    branches: [main, develop]
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.json'
      - '**/*.jsonc'
      - '**/*.vue'
      - '**/*.astro'
      - '**/*.svelte'
      - 'biome.json'
      - 'biome.jsonc'

jobs:
  biome:
    name: Run Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.6.0
        with:
          version: latest

      - name: Run Biome check
        run: biome check .
        continue-on-error: false
